var item1 = document.getElementById("item1");
var item2 = document.getElementById("item2");
var item3 = document.getElementById("item3");
var item4 = document.getElementById("item4");
var info1 = document.getElementById("info1");
var info2 = document.getElementById("info2");

item1.addEventListener("click", function(){
    info1.innerHTML = "<p style='margin-left:35%; id='1dinfo' > One Direction, a British-Irish pop boy band, was formed on July 23, 2010, on the British television series, The X Factor. Each of the members, Harry Styles, Liam Payne, Niall Horan, Louis Tomlinson, and Zayn Malik, auditioned for the show individually but none of them qualified to the next segment of the show, the judge's houses. However, head judge, Simon Cowell, thought these boys were too talented to give up and put them into a group so that they could go to the judge's houses under the band category. Styles came up with the name One Direction and the band made it all the way to the finals, where they placed third. Despite their placement, Simon Cowell still signed them to his label. They had gained hundreds of extremely dedicated fans in the UK and across Europe while on the show. These fans quickly spread the word about One Direction, and they were soon one of the most talked about bands all over the world. The band gained major popularity across the world with the release of their first single, <i>What Makes You Beautiful</i>. Since 2010, One Direction have made 5 albums that have all debuted at #1 on the iTunes charts in the UK, the only band to do this in history. They have also gone on 5 world tours, and won countless awards. In March of 2015, while in the middle of one of their world tours, band member Zayn Malik quit the band and flew home to England, saying that he felt he could not be himself while in One Direction and that he was simply overworked and overwhelmed. While this was a major shock to the other four boys and the millions of fans, Harry, Liam, Niall, and Louis continued with and completed the rest of the tour. However, late in 2015, the four boys announced that they would be going on a well earned hiatus. They have promised multiple times that they will be back after this hiatus and many of their loyal fans believe them and trust that they will continue to make music as One Direction after their break. You can buy One Direction's latest album, <i>Made In The AM</i>, on iTunes now.</p>";
    info2.innerHTML = "<p style='margin-left:20%; margin-top:40px' id='1dinfo2' >  </p>";
});
                      
item2.addEventListener("click", function(){
    info1.innerHTML = "<p style='margin-left:35%; id='5sosinfo' > 5 Seconds of Summer, often called 5sos, is an Australian pop-punk band that formed in 2011. Band members Luke Hemmings, Ashton Irwin, Calum Hood, and Michael Clifford, all went to school together in Sydney. Luke was the first to make his singing public, posting videos of himself singing to various songs on YouTube. Michael, Calum, and Ashton soon joined him and they formed a band. The group originally posted videos of themselves covering songs on YouTube where they gained many faithful fans. 5sos gained international popularity when Louis Tomlinson of One Direction, a band who already had millions of fans across the world, tweeted a link to a video of their own song, <i>Gotta Get Out</i>, on YouTube. Louis also said that he had been a big fan of the band for a while. Many One Direction fans then became 5sos fans as well and their popularity increased even more when another member of One Direction, Niall Horan, tweeted a link to a video of the band's first single, <i>Out of My Limit</i>. The next year, 2013, 5sos joined One Direction on their Take Me Home world tour as their opening act. Due to popular demand, One Direction asked 5sos to open for them again on their Where We Are world tour in 2014. After this tour, 5sos had gained many fans, popularity across the world, and signed a record deal with Capitol Records. They announced their own world tour in 2015, the Rock Out With Your Socks Out tour, often abbreviated as the ROWYSO tour. This tour was very successfull and the band announced in late 2015 that they would be going on another world tour in 2016, even bigger than before. You can buy 5 Seconds Of Summer's latest album, <i>Sounds Good Feels Good</i>, on iTunes now. </p>";
    info2.innerHTML = "<p style='margin-left:20%; margin-top:40px' id='5sosinfo2'> </p>";
});

item3.addEventListener("click", function(){
    info1.innerHTML = "<p style='margin-top:30%; margin-left:35%; id='coldplayinfo' > Coldplay, another British band, has been around since 1996, which is 20 years. Coldplay is considered by many to be a rock band. The band was formed by lead singer, Chris Martin, and lead guitarist, Johnny Buckland. They bagan playing together in 1996 at University College London. Initially, these two named their band Pectoralz. When bassist, Guy Berryman, joined the group, they renamed the band Starfish. Finally, in 1998, when drummer, backing vocalist, and multi-instrumentalist, Will Champion, joined the band, it was renamed Coldplay. Later in 1998, the band released three EPs, short for extended plays, and signed a record deal with Parlophone record label. Their first single, <i>Yellow</i>, made them internationally popular. This popularity increased with the release of their first album, Parachutes. This album did extremely well, winning a Grammy Award for Best Alternative Music Album in 2002. It also won the Best British Album Award at the Brit Awards in 2001. Coldplay has sold 8.5 milion copies of Parachutes worldwide as of 2011. The band's following albums, <i>A Rush of Blood to the Head</i>, <i>X&Y</i>, <i>Viva La Vida or Death and All His Friends</i>, <i>Mylo Xyloto</i>, <i>Ghost Stories</i>, and <i>A Head Full of Dreams</i>, have all done well on the charts also. For these albums, Coldplay has gone on seven tours all around the world. As well as being big in the music industry, Coldplay have been active supporters of social, political, and charitable causes.   You can buy Coldplay's latest album, <i>A Head Full of Dreams</i>, on iTunes now.</p>";
    info2.innerHTML = "<p style='margin-left:20%; margin-top:40px' id='coldplayinfo2'> </p>";
});

item4.addEventListener("click", function(){
    info1.innerHTML = "<p style='margin-top:40%; margin-left:35%; id='littlemixinfo' > Little Mix is a British girl group formed on the popular British singing series, The X Factor. Each of the four members, Jade Thirlwall, Perrie Edwards, Leigh-Ann Pinnock, and Jesy Nelson auditioned as individuals initially. They were all put together as a band on the show in 2011 and as of today are the only band to have won the show ever. After winning the show, they signed with Syco Record Label, owned by Simon Cowell. Since 2011, Little Mix have produced three albums and a tour for each album. Little Mix has sold millions of copies of all of their albums across the world. They are often associated with One Direction as both bands are British and were both formed on the X Factor. Also, Perrie Edward and Zayn Malik became engaged in August 2013, relsulting in the members from both bands becoming very close. Their fans also began to support both bands if they did not already. Perrie and Zayn, although still engaged, did not get married and their relationship was part of the reason why Zayn left One Direction. When rumours spread about Zayn cheating on Perrie with an anonymous girl, he got fed up and left the band, stating that he did not want to be in the spotlight and wanted to sort things out with Perrie. In August 2015, five months after Zayn left One Direction, the couple broke up. Perrie's fellow band members as well as fans of both bands showed their support for her, spreading love and encouragement through social media. Little Mix kicked off their 2016 world tour on March 13, earlier this year. The group will perform shows throughout Europe, Asia, and Australia. You can buy their latest album, <i> Get Weird, </i> on iTunes now. </p>";
});

